CREATE TABLE IF NOT EXISTS "Superstore" (
  id SERIAL PRIMARY KEY,
  "order_id" TEXT,
  "order_date" DATE,
  "ship_date" DATE,
  "ship_mode" TEXT,
  "customer_name" TEXT,
  "segment" TEXT,
  "state" TEXT,
  "country" TEXT,
  "market" TEXT,
  "region" TEXT,
  "product_id" TEXT,
  "category" TEXT,
  "sub_category" TEXT,
  "product_name" TEXT,
  "sales" TEXT,
  "quantity" INTEGER,
  "discount" DOUBLE PRECISION,
  "profit" DOUBLE PRECISION,
  "shipping_cost" DOUBLE PRECISION,
  "order_priority" TEXT,
  "year" INTEGER
);